# Default values for nginx-ingress.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: demo-ovr

replicaCount: 3

deployment:
  namespace: demo

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
