apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "demo.fullname" . }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "demo.selectorLabels" . | nindent 6 }}
  replicas: 3
  template:
    metadata:
      labels:
        {{- include "demo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: "demo"
        image: "mjagyo/test-node:1.0.0"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 4004
        livenessProbe:
          httpGet:
            path: /api/health
            port: 4004
            scheme: HTTP
          initialDelaySeconds: 30
          timeoutSeconds: 5
          failureThreshold: 2
  