apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-ing
  namespace: {{ .Values.deployment.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /(.+)
            pathType: Prefix
            backend:
              service:
                name: {{ include "demo.fullname" . }}
                port: 
                  number: 4004
