apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo.fullname" . }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    {{- include "demo.labels" . | nindent 4 }}
spec:
  ports:
    - port: 4004
      targetPort: 4004
      protocol: TCP
      name: http
  selector:
    {{- include "demo.selectorLabels" . | nindent 4 }}
